### ISSUE TITLE
Build process blocks UI until it completes

### ISSUE THREAD

**Issue by plmcgrn** [macmule/AutoCasperNBI#100]
I've seen this with apps (mostly Windows), where there is some long-running process that blocks/freezes the UI until it completes.  This seems to happen at the "Copying the contents of the OS.dmg to NetBoot.sparseimage).  This is a progress bar that displays on top of all other UI elements on the Mac, and spinners when trying to relocate it.

Is it possible to make this window movable/non-blocking, since this is definitely a long-running task?
![image](https://cloud.githubusercontent.com/assets/889547/23170121/289bdbd6-f81c-11e6-8c2c-ac5bc819495e.png)

**Comment by macmule** [comment]
@plmcgrn AutoCasperNBI is currently single-threaded. To make the change you're looking for requires the app to be changed to multi-threaded & is not that simple a change I'm afraid.

I'd love to do it, but it's not going to be easy.

**Comment by plmcgrn** [comment]
Fair enough.  Any way to at least tweak it so the progress bar isn't always on top?

**Comment by macmule** [comment]
@plmcgrn nope.. sadly
