### ISSUE TITLE
System Preference "Keyboard" missing when "Reduce Image Size" is selected

### ISSUE THREAD

**Issue by entusdictus** [macmule/AutoCasperNBI#101]
When choosing the "Reduce Image Size" option, the "Keyboard" prefpane is missing. 
For example, when building a NetBoot set that has to be used all over the world in different countries with different keyboard layouts, the correct keyboard layout cannot be selected because of the missing prefpane. Please do not remove this prefpane in order to fix this.

**Comment by macmule** [comment]
@entusdictus Sounds reasonable.

I'll be doing an update in time for 10.13, so will look to add this in then.

**Comment by macmule** [comment]
in 1.4.0
