### ISSUE TITLE
AutoCasperNBI 1.3.4 not picking up Casper Imaging 9.99

### ISSUE THREAD

**Issue by mrperrott** [macmule/AutoCasperNBI#102]
When selecting the Casper Imaging 9.99 app, AutoCasperNBI seems to get stuck on 'Examining'.

<img width="278" alt="autocaspernbi" src="https://user-images.githubusercontent.com/30660444/28877642-fb445cd4-776a-11e7-8275-1d764651e4d0.png">

**Comment by macmule** [comment]
@mrperrott I've not been able to replicate this at all.
