### ISSUE TITLE
Jamf Imaging 10.0

### ISSUE THREAD

**Issue by TinyAtJamf** [macmule/AutoCasperNBI#104]
Hey Ben,

Just wanted to give you a heads up. I am doing some testing building NBIs and making sure everything is good with the 10.0 Imaging, and noticed a problem.

With the release of Jamf 10.0, it is switching from Casper Imaging to Jamf Imaging.

As of right now, selecting the Jamf Imaging app ends up with it not recognizing the App. If you already have this on your radar, feel free to close this, just thought I would send this your way.

![screen shot 2017-09-06 at 12 26 03 pm](https://user-images.githubusercontent.com/27296122/30125626-9a153870-92fe-11e7-8688-922f525731d5.png)

**Comment by macmule** [comment]
thanks @TinyAtJamf.

I'm actually working on 10.13 support as well as v10 & downloaded the DMG this AM :)

Hit a snag with 10.13: [http://openradar.appspot.com/radar?id=6057042104025088](http://openradar.appspot.com/radar?id=6057042104025088)

But will add Jamf Imaging.app support with next release that should be out come JNUC.

I'll likely have some betas for folks to test, so keep an eye out here or reach out to me on Slack.
