### ISSUE TITLE
10.13 NBI: Take 8+ minutes to boot

### ISSUE THREAD

**Issue by macmule** [macmule/AutoCasperNBI#109]
Looks to be an Apple issue, recreated with SIU.

## Open Radar

As per: [http://www.openradar.me/34251768](http://www.openradar.me/34251768)

## Summary:
10.13 NetBoot images created with SIU from a beta 8, 9 source take 8+ minutes to boot.

## Steps to Reproduce:
1) Create a NetBoot Image with SIU with a Beta 8 or 9 APFS volume as the source
2) Time how long booting to the NetBoot takes (from boot to loginwindow).

## Expected Results:
10.12.x same hardware is 3-4 minutes

## Actual Results:
8-9 minutes but boot does complete

## Version:
10.13

## Notes:
In my testing the source DMG was created with AutoDMG

## Comments
Issue persists in release

**Comment by beezoncheg** [comment]
Today Apple has released Server 5.5 with fixes for NetBoot.
10.13.2 image it boots over HTTP in exactly 4 minutes on MacBook Air. Seems that they are fixed this issue (finger crossed)

**Comment by macmule** [comment]
Looks to have been resolved within a more recent 10.13.x update
