### ISSUE TITLE
Build Greyed out when major version difference

### ISSUE THREAD

**Issue by macmule** [macmule/AutoCasperNBI#112]
<img width="554" alt="screen shot 2017-12-20 at 3 13 21 pm" src="https://user-images.githubusercontent.com/2464974/34256799-e528a178-e64e-11e7-85e9-6ae91fcf5b46.png">

**Comment by hkabik** [comment]
I am seeing this issue in 10.13.6

**Comment by macmule** [comment]
@hkabik should be fixed in 1.5.0
