### ISSUE TITLE
System Administrator Security & Privacy Setting

### ISSUE THREAD

**Issue by ctarbox** [macmule/AutoCasperNBI#113]
AutoCasperNBI Version 1.4.1

The System Administrator's Security & Privacy Setting --> Require password immediately after sleep or screen saver begins is checked. This results in the Netboot set going to a lock screen at sleep. I cannot find where in the netboot set this is triggered as:
ScreenSaver is set to: Never
Energy Saver is set to: Prevent computer from sleeping automatically...
Energy Saver: Put hard disks to sleep is not set

I also do not know what the time frame is based off of for the lock screen to activate.

I have never come across this before with your software. Could you adjust this to not go to lock screen?

**Comment by ctarbox** [comment]
Good Morning!

10.13.4

Cheryl Tarbox
Macintosh System Administrator
LN G101
Binghamton University
ITS Technology Support Services
ctarbox@binghamton.edu <mailto:ctarbox@binghamton.edu>
(607) 777-2870

**Comment by macmule** [comment]
Morning!

So the change will be with that OS then, will have to dig around when able.

If you could find the plist for that setting, that would be a great help.

**Comment by ctarbox** [comment]
I see. I will look for the plist and send it off to you when/if I find it. I’m just starting to build new Netboot sets with 10.13.4. I do want to report that I am NOT seeing the 8+ minute boot times. My netboot sets are booting at around 3 min, which is about the same as my El Cap and Sierra netboot sets.

FYI — This doesn’t kick in immediately. I left a test client at the netboot screen when I left work yesterday. When I returned this morning, it was at the lock screen.

Thanks for your quick attention to this. 

Cheryl Tarbox
Macintosh System Administrator
LN G101
Binghamton University
ITS Technology Support Services
ctarbox@binghamton.edu <mailto:ctarbox@binghamton.edu>
(607) 777-2870

**Comment by macmule** [comment]
Thanks for the timing report :)

If you find the plist, you can create a pkg that writes it out as needed then add that when creating your NBI as an interim fix.

**Comment by ctarbox** [comment]
I netbooted a client around 9:30 AM, and it’s still logged it at 10:15. If it proves to be that there is many hours before the screen locks, I’ll be OK with it as is.

Cheryl Tarbox
Macintosh System Administrator
LN G101
Binghamton University
ITS Technology Support Services
ctarbox@binghamton.edu <mailto:ctarbox@binghamton.edu>
(607) 777-2870

**Comment by macmule** [comment]
Closing as should be ok as-is

**Comment by ctarbox** [comment]
Thank you!
