### ISSUE TITLE
Build and options greyed out with 10.13.6

### ISSUE THREAD

**Issue by hkabik** [macmule/AutoCasperNBI#114]
![screen shot 2018-08-02 at 5 45 30 pm](https://user-images.githubusercontent.com/21319356/43612980-e851dc7e-967b-11e8-9b04-8f63469e34c1.png)

**Comment by wmehilos** [comment]
Did you point it to an Imaging app before selecting an OS.dmg? If so, try selecting the Imaging app again, I had the same issue and it re-enabled the rest of the options.

**Comment by macmule** [comment]
Can reproduce :( Will sort

**Comment by macmule** [comment]
fixed in 1.5.0
