### ISSUE TITLE
Trying to build with a 10.14 OS.dmg fails

### ISSUE THREAD

**Issue by ehemmete** [macmule/AutoCasperNBI#115]
The app reports that it cannot read OS version with a 10.14 18A391 apfs dmg from AutoDMG, but this appears to be cosmetic.
When trying to build the process stops with error "Disabling Software Update". 

The log file shows:
Thu Oct 4 09:01:26 CDT 2018 Deleting /Volumes/JLL_JAMF_Imaging_10.7.1/System/Library/CoreServices/Software Update.app
Thu Oct 4 09:01:27 CDT 2018 Deleted /Volumes/JLL_JAMF_Imaging_10.7.1/System/Library/CoreServices/Software Update.app
Thu Oct 4 09:01:27 CDT 2018 Deleting /Volumes/JLL_JAMF_Imaging_10.7.1/System/Library/LaunchDaemons/com.apple.softwareupdate*
Thu Oct 4 09:01:27 CDT 2018 Error: Disabling Software Update

Is there a way to change the Always Set options?  I'm curious if turning off the software update disable would let AutoCasperNBI proceed.

**Comment by macmule** [comment]
@ehemmete I cannot recreate with a release version of Mojave.. but have been updating AutoCasperNBI.

I'll ping you a copy on Slack, if you can test this week that would be great!

Hoping to release soon
