### ISSUE TITLE
Mojave Custom Desktop

### ISSUE THREAD

**Issue by ehemmete** [macmule/AutoCasperNBI#122]
With a macOS 10.14.1 (18B75) base image, the custom Desktop image is not being shown when the NBI is used.  The file is copied over properly to /System/Library/CoreServices/DefaultDesktop.jpg, but doesn't seem to be used. On the NBI there are symbolic links in that same directory that seem to take precedence.  System Preferences shows that the Dynamic Mojave.heic is what is used by the system.
lrwxr-xr-x    1 root           wheel  restricted              40B Nov  1 15:23 DefaultBackground.jpg@ -> /Library/Desktop Pictures/Mojave Day.jpg
lrwxr-xr-x    1 root           wheel  restricted              37B Nov  1 15:23 DefaultDesktop.heic@ -> /Library/Desktop Pictures/Mojave.heic

**Comment by macmule** [comment]
In 1.5.1
