### ISSUE TITLE
Image app selection doesn't seem to work

### ISSUE THREAD

**Issue by arj22** [macmule/AutoCasperNBI#124]
When I select the Casper Imaging app, the logs suggest that the app has been selected but the AutoCasperNBI doesn't show a change and thus the other options are greyed out.

```
Sat May 4 03:09:38 EDT 2019 AutoCasperNBI 1.5.0
Sat May 4 03:09:38 EDT 2019 Running on OS 10.14.4 (18E226)
Sat May 4 03:09:38 EDT 2019 Launched by user
Sat May 4 03:09:38 EDT 2019 UUID 410D6AC0-59C7-4187-A4D5-7F2DD40F6156
Sat May 4 03:09:38 EDT 2019 NetBoot is to be hosted on a single server.
Sat May 4 03:09:50 EDT 2019 Path: /Users/username/Downloads/osx-10.14.4-18E227.apfs.dmg
Sat May 4 03:09:50 EDT 2019 Trying to mount: /Users/username/Downloads/osx-10.14.4-18E227.apfs.dmg
Sat May 4 03:09:50 EDT 2019 Mounted to: /Volumes/Macintosh HD 1
Sat May 4 03:10:01 EDT 2019 Selected App Path: /Users/username/Downloads/Casper NetInstall Image Creator.app/
Sat May 4 03:10:01 EDT 2019 Bundle Name: Casper NetInstall Image Creator
Sat May 4 03:10:01 EDT 2019 Select an Imaging.app
Sat May 4 03:10:12 EDT 2019 Selected App Path: /Users/username/Downloads/Casper NetInstall Image Creator.app/
Sat May 4 03:10:12 EDT 2019 Bundle Name: Casper NetInstall Image Creator
Sat May 4 03:10:12 EDT 2019 Select an Imaging.app
```

![image](https://user-images.githubusercontent.com/16482322/57175926-cf271f80-6e1f-11e9-87ee-18d577e62019.png)

OS version: 10.14.4 Mojave
Casper app version: 6.0.1

**Comment by macmule** [comment]
@arj22 the imaging apps needs to be Casper Imaging.app or Jamf Imaging.app.

Looks like you tried Casper NetInstall Creator.app

> Sat May 4 03:10:12 EDT 2019 Selected App Path: /Users/username/Downloads/Casper NetInstall Image Creator.app/
> Sat May 4 03:10:12 EDT 2019 Bundle Name: Casper NetInstall Image Creator
