### ISSUE TITLE
Create a nbi with autocaspernbi and "InstallESD.dmg" of Mojave install

### ISSUE THREAD

**Issue by dfuriet** [macmule/AutoCasperNBI#125]
Hi,

I have problem with aitocaspernbi and InstallESD.dmg of a Mojave install : when I select InstallESD.dmg, I'ts said : Cannot read OS Version. It's not possible to use this dmg ?

I've tried to create nbi with a autodmg for using with autocaspernbi, but my nbi is too big to download on Netboot

My autocaspernbi is 1.5.2

Thanks

**Comment by macmule** [comment]
@dfuriet You don't give AutoCasperNBI a InstallSED.dmg, but an AutoDMG created OS.dmg.

**Comment by dfuriet** [comment]
Ok, but how to reduce dmg ?
