### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by rhs615** [macmule/AutoCasperNBI#14]
First, taking a fresh OS.dmg file (actually got it from a JAMF CCA course), I get the error of Could Not Find OS Version. If I mount the DMG before opening AutoCasperNBI, it gives me the green light, however it sees the version of my OS, not the mounted DMG. I then get green lights on everything and go to build to my desktop and it fails everytime with Error: Cannot copy contents of to '/Volumes/AutoCasperNBI'. I see it make the .nbi folder, and mount the NetBoot.dmg within it, but then cannot copy anything. 

I've even tried having the DMG mounted when opening CasperNBI to get the version check green light, and then unmounting before hitting build to see if it needs to mount it fresh for the copy.

Fri Jan 23 10:09:24 EST 2015 AutoCasperNBI 1.1.4
Fri Jan 23 10:09:24 EST 2015 Running on OS 10.9.5 (13F34)
Fri Jan 23 10:09:24 EST 2015 Launched by rshore
Fri Jan 23 10:09:24 EST 2015 UUID 2530EF76-5031-4D9B-B5E1-0AE13AA5D3EF
Fri Jan 23 11:26:42 EST 2015 Trying to detach 
Fri Jan 23 11:26:42 EST 2015 Trying to detach 
Fri Jan 23 11:26:42 EST 2015 Trying to detach 
Fri Jan 23 11:26:42 EST 2015 Goodbye for now!

Fri Jan 23 15:26:15 EST 2015 AutoCasperNBI 1.1.4
Fri Jan 23 15:26:15 EST 2015 Running on OS 10.9.5 (13F34)
Fri Jan 23 15:26:15 EST 2015 Launched by rshore
Fri Jan 23 15:26:15 EST 2015 UUID 0B412CBA-C924-4A40-9DCE-6E9C48148DE7
Fri Jan 23 15:26:19 EST 2015 User rshore is part of the Administrators group
Fri Jan 23 15:26:50 EST 2015 Path: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/Macintosh HD.dmg
Fri Jan 23 15:26:50 EST 2015 Trying to mount: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/Macintosh HD.dmg
Fri Jan 23 15:27:39 EST 2015 Cannot read OS Version
Fri Jan 23 15:28:11 EST 2015 Selected App Path: /Applications/Casper Suite/Casper Imaging.app/
Fri Jan 23 15:28:11 EST 2015 Bundle Name: Casper Imaging
Fri Jan 23 15:28:11 EST 2015 Casper Imaging Version: 9.62
Fri Jan 23 15:28:11 EST 2015 NetBoot is to be hosted on a single server.
Fri Jan 23 15:28:16 EST 2015 Path: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/Macintosh HD.dmg
Fri Jan 23 15:28:16 EST 2015 Trying to mount: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/Macintosh HD.dmg
Fri Jan 23 15:28:18 EST 2015 Cannot read OS Version
Fri Jan 23 15:29:04 EST 2015 Path: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/Macintosh HD.dmg
Fri Jan 23 15:29:04 EST 2015 Trying to mount: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/Macintosh HD.dmg
Fri Jan 23 15:29:06 EST 2015 Cannot read OS Version
Fri Jan 23 15:31:49 EST 2015 Path: /Users/rshore/Desktop/Macintosh HD.dmg
Fri Jan 23 15:31:49 EST 2015 Trying to mount: /Users/rshore/Desktop/Macintosh HD.dmg
Fri Jan 23 15:32:35 EST 2015 Cannot read OS Version
Fri Jan 23 15:33:05 EST 2015 Trying to detach 
Fri Jan 23 15:33:05 EST 2015 Trying to detach 
Fri Jan 23 15:33:05 EST 2015 Trying to detach HD 2
Fri Jan 23 15:33:05 EST 2015 Goodbye for now!

Fri Jan 23 15:34:11 EST 2015 AutoCasperNBI 1.1.4
Fri Jan 23 15:34:11 EST 2015 Running on OS 10.9.5 (13F34)
Fri Jan 23 15:34:11 EST 2015 Launched by rshore
Fri Jan 23 15:34:11 EST 2015 UUID BDFD3656-7DBC-475F-BF60-CAC252632C02
Fri Jan 23 15:34:15 EST 2015 User rshore is part of the Administrators group
Fri Jan 23 15:34:21 EST 2015 Path: /Users/rshore/Desktop/Macintosh HD.dmg
Fri Jan 23 15:34:21 EST 2015 Trying to mount: /Users/rshore/Desktop/Macintosh HD.dmg
Fri Jan 23 15:34:23 EST 2015 Cannot read OS Version
Fri Jan 23 15:34:41 EST 2015 Selected App Path: /Applications/Casper Suite/Casper Imaging.app/
Fri Jan 23 15:34:41 EST 2015 Bundle Name: Casper Imaging
Fri Jan 23 15:34:41 EST 2015 Casper Imaging Version: 9.62
Fri Jan 23 15:34:41 EST 2015 NetBoot is to be hosted on a single server.
Fri Jan 23 15:44:26 EST 2015 Path: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/OS.dmg
Fri Jan 23 15:44:26 EST 2015 Trying to mount: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/OS.dmg
Fri Jan 23 15:44:28 EST 2015 Cannot read OS Version
Fri Jan 23 16:05:00 EST 2015 Path: /Users/rshore/Desktop/OS.dmg
Fri Jan 23 16:05:00 EST 2015 Trying to mount: /Users/rshore/Desktop/OS.dmg
Fri Jan 23 16:05:02 EST 2015 Cannot read OS Version
Fri Jan 23 16:07:01 EST 2015 Trying to detach 
Fri Jan 23 16:07:01 EST 2015 Trying to detach 
Fri Jan 23 16:07:01 EST 2015 Trying to detach HD 2
Fri Jan 23 16:07:01 EST 2015 Goodbye for now!

Fri Jan 23 16:47:43 EST 2015 AutoCasperNBI 1.1.4
Fri Jan 23 16:47:43 EST 2015 Running on OS 10.9.5 (13F34)
Fri Jan 23 16:47:44 EST 2015 Launched by rshore
Fri Jan 23 16:47:44 EST 2015 UUID 4D1606FF-9CC5-46D1-8E50-144FD38BCD96
Fri Jan 23 16:49:08 EST 2015 User ots is part of the Administrators group
Fri Jan 23 16:49:14 EST 2015 Path: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/OS.dmg
Fri Jan 23 16:49:14 EST 2015 Trying to mount: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/OS.dmg
Fri Jan 23 16:49:17 EST 2015 NetBoot Name: 10.9.5 AutoCasperNBI
Fri Jan 23 16:49:17 EST 2015 NetBoot is to be hosted on a single server.
Fri Jan 23 16:49:27 EST 2015 Selected App Path: /Applications/Casper Suite/Casper Imaging.app/
Fri Jan 23 16:49:27 EST 2015 Bundle Name: Casper Imaging
Fri Jan 23 16:49:27 EST 2015 Casper Imaging Version: 9.62
Fri Jan 23 16:49:27 EST 2015 NetBoot is to be hosted on a single server.
Fri Jan 23 16:49:27 EST 2015 Pre-Reqs met, Options & Build enabled.
Fri Jan 23 16:49:34 EST 2015 Trying to get JSS version
Fri Jan 23 16:49:34 EST 2015 Received JSS version
Fri Jan 23 16:49:34 EST 2015 Checking JSS Version from https://jss.columbian.gwu.edu
Fri Jan 23 16:49:34 EST 2015 Cannot get JSS Version
Fri Jan 23 16:49:37 EST 2015 Trying to get JSS version
Fri Jan 23 16:49:37 EST 2015 Received JSS version
Fri Jan 23 16:49:37 EST 2015 Checking JSS Version from https://jss-admin.columbian.gwu.edu
Fri Jan 23 16:49:37 EST 2015 JSS is: 9.62
Fri Jan 23 16:49:37 EST 2015 Pre-Reqs met, Options & Build enabled.
Fri Jan 23 16:49:41 EST 2015 NetBoot Name: AutoCasperNBI
Fri Jan 23 16:49:43 EST 2015 Trying to get JSS version
Fri Jan 23 16:49:43 EST 2015 Received JSS version
Fri Jan 23 16:49:43 EST 2015 Checking JSS Version from https://jss-admin.columbian.gwu.edu
Fri Jan 23 16:49:43 EST 2015 JSS is: 9.62
Fri Jan 23 16:49:43 EST 2015 Pre-Reqs met, Options & Build enabled.
Fri Jan 23 16:49:43 EST 2015 NetBoot Name: AutoCasperNBI
Fri Jan 23 16:49:43 EST 2015 NetBoot description not enabled
Fri Jan 23 16:49:46 EST 2015 ARD Username written to plist
Fri Jan 23 16:49:48 EST 2015 ARD password written to plist
Fri Jan 23 16:49:50 EST 2015 ARD Username written to plist
Fri Jan 23 16:49:54 EST 2015 NetBoot description enabled
Fri Jan 23 16:49:54 EST 2015 NetBoot description set to 'Mac OS 10.9.5 (13F34) with Casper Imaging 9.62 pointing to JSS https://jss-admin.columbian.gwu.edu. Created by, Randall H. Shore on: Friday, January 23, 2015.'
Fri Jan 23 16:49:55 EST 2015 ARD password written to plist
Fri Jan 23 16:50:03 EST 2015 Time Zone selected: Americas/Los_Angeles
Fri Jan 23 16:50:11 EST 2015 Time Zone selected: America/New_York
Fri Jan 23 16:50:13 EST 2015 ARD Username written to plist
Fri Jan 23 16:50:13 EST 2015 ARD password written to plist
Fri Jan 23 16:50:13 EST 2015 Time Server: time.apple.com
Fri Jan 23 16:50:14 EST 2015 NetBoot Name: AutoCasperNBI
Fri Jan 23 16:50:15 EST 2015 Trying to get JSS version
Fri Jan 23 16:50:15 EST 2015 Received JSS version
Fri Jan 23 16:50:15 EST 2015 Checking JSS Version from https://jss-admin.columbian.gwu.edu
Fri Jan 23 16:50:15 EST 2015 JSS is: 9.62
Fri Jan 23 16:50:15 EST 2015 Pre-Reqs met, Options & Build enabled.
Fri Jan 23 16:50:15 EST 2015 NetBoot description enabled
Fri Jan 23 16:50:15 EST 2015 NetBoot description set to 'Mac OS 10.9.5 (13F34) with Casper Imaging 9.62 pointing to JSS https://jss-admin.columbian.gwu.edu. Created by, Randall H. Shore on: Friday, January 23, 2015.'
Fri Jan 23 16:50:21 EST 2015 Selected path to create .nbi is: /Users/rshore/Desktop/
Fri Jan 23 16:50:21 EST 2015 Trying to get the Total size of ''
Fri Jan 23 16:50:21 EST 2015 Total size of '' is 0GB rounded up
Fri Jan 23 16:50:21 EST 2015 There is around 0GB space free on '' rounded down
Fri Jan 23 16:50:21 EST 2015 Used space on '' is around 0GB
Fri Jan 23 16:50:21 EST 2015 The NetBoot.dmg will need to be around 1GB
Fri Jan 23 16:50:21 EST 2015 Checking for free space on /
Fri Jan 23 16:50:22 EST 2015 The volume / has 10GB free, rounding down
Fri Jan 23 16:50:22 EST 2015 We need around 1GB free to create the NBI.
Fri Jan 23 16:50:22 EST 2015 Trying to create .nbi folder /Users/rshore/Desktop/AutoCasperNBI.nbi
Fri Jan 23 16:50:22 EST 2015 Successfully created '/Users/rshore/Desktop/AutoCasperNBI.nbi'
Fri Jan 23 16:50:22 EST 2015 Trying to create NetBoot.dmg in /Users/rshore/Desktop/AutoCasperNBI.nbi
Fri Jan 23 16:50:26 EST 2015 Successfully created NetBoot.dmg in '/Users/rshore/Desktop/AutoCasperNBI.nbi'
Fri Jan 23 16:50:27 EST 2015 Trying to mount: '/Users/rshore/Desktop/AutoCasperNBI.nbi'
Fri Jan 23 16:50:28 EST 2015 Mounted to: /Volumes/AutoCasperNBI
Fri Jan 23 16:50:28 EST 2015 Copying contents of '' to '/Users/rshore/Desktop/AutoCasperNBI.nbi'/NetBoot.dmg
Fri Jan 23 16:50:28 EST 2015 Error: Cannot copy contents of  to '/Volumes/AutoCasperNBI'
Fri Jan 23 17:05:07 EST 2015 Trying to detach /Volumes/AutoCasperNBI
Fri Jan 23 17:05:17 EST 2015 Trying to detach 
Fri Jan 23 17:05:17 EST 2015 Trying to detach 
Fri Jan 23 17:05:17 EST 2015 Goodbye for now!

Fri Jan 23 17:05:50 EST 2015 AutoCasperNBI 1.1.4
Fri Jan 23 17:05:50 EST 2015 Running on OS 10.9.5 (13F34)
Fri Jan 23 17:05:50 EST 2015 Launched by rshore
Fri Jan 23 17:05:50 EST 2015 UUID D2C2CE8E-C228-4D39-8D02-28B271760A4C
Fri Jan 23 17:05:59 EST 2015 User rshore is part of the Administrators group
Fri Jan 23 17:06:10 EST 2015 Path: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/Macintosh HD.dmg
Fri Jan 23 17:06:10 EST 2015 Trying to mount: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/Macintosh HD.dmg
Fri Jan 23 17:06:12 EST 2015 Cannot read OS Version
Fri Jan 23 17:06:44 EST 2015 Trying to detach 
Fri Jan 23 17:06:44 EST 2015 Trying to detach 
Fri Jan 23 17:06:44 EST 2015 Trying to detach HD 1
Fri Jan 23 17:06:44 EST 2015 Goodbye for now!

Fri Jan 23 17:06:50 EST 2015 AutoCasperNBI 1.1.4
Fri Jan 23 17:06:50 EST 2015 Running on OS 10.9.5 (13F34)
Fri Jan 23 17:06:50 EST 2015 Launched by rshore
Fri Jan 23 17:06:50 EST 2015 UUID 5FABE5F4-70AF-4647-BE10-E575496B62CE
Fri Jan 23 17:07:03 EST 2015 User ots is part of the Administrators group
Fri Jan 23 17:07:03 EST 2015 Authentication failed for user: ots
Fri Jan 23 17:07:07 EST 2015 User ots is part of the Administrators group
Fri Jan 23 17:07:12 EST 2015 Path: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/Macintosh HD.dmg
Fri Jan 23 17:07:12 EST 2015 Trying to mount: /Users/rshore/Desktop/CCA Stuff/CCA resources/Lesson 37/Macintosh HD.dmg
Fri Jan 23 17:07:13 EST 2015 Cannot read OS Version

**Comment by macmule** [comment]
Hi Randall,

Can you mount the DMG via Finder?

AutoCasperNBI attempts to read the OS version information from /System/Library/CoreServices/SystemVersion.plist. Is that present?

Regards,

Ben.

**Comment by rhs615** [comment]
Hi Ben,

I just reran the installer through AutoPKG, and it appears to be working now! I guess it was a corrupt .dmg somehow? 

Thanks for the help!

Randy Shore

**Comment by macmule** [comment]
Yea it seems to be the way. 

Hmm.. I'm working on the next version, i'll see if I can get some better errors when mounting fails. 

You wouldn't happen to be able to upload the "bad" OS.dmg somewhere that I could download it?

Regards,

Ben.
