### ISSUE TITLE
NetBoot Image Description does not get written to NBImageInfo.plist

### ISSUE THREAD

**Issue by hunty1** [macmule/AutoCasperNBI#15]
Not a big deal by any means but I've noticed that any text entered into the NetBoot Description field does not make it into the final NBImageInfo.plist.

Only the auto generated text gets written out to the NBImageInfo.plist

![screen shot 2015-01-28 at 10 45 18 am](https://cloud.githubusercontent.com/assets/7887711/5929730/c796c308-a6da-11e4-87fb-a08cb300d2f8.png)

**Comment by macmule** [comment]
Fixed in 1.1.5, it was a mess in there tbh.
