### ISSUE TITLE
10.9.x NBI created in 10.10.x won't boot

### ISSUE THREAD

**Issue by peterquest** [macmule/AutoCasperNBI#16]
Created a 10.9.5 NBI using a base OS.dmg created with AutoDMG on a machine running 10.10.2.

Any time I try to boot using this nbi, I get 'Error loading kernelcache (0xe)' despite the fact that kernelcache is in the proper location with the proper permissions.

**Comment by justinrummel** [comment]
I thought best practices would be use the same OS for all.  Thus:

While running Mavericks, create a OSX-10.9.5.dmg via AutoDMG, then create a 10.9.5 nbi using AutoCasperNBI.

**Comment by peterquest** [comment]
I knew that was the case for AutoDMG, but I wasn't sure if that applied to AutoCasperNBI as well (though I'm not sure why it wouldn't..)

I can confirm that using a 10.10.1 OS.dmg worked as intended.

**Comment by peterquest** [comment]
from ##osx-server on freenode:

11:10 <@macmule> p_q: cool.. so it's 10.10 creating a 10.9 NBI then.. please log an issue!
11:11 <@macmule> p_q: i suspect the issue is the cache reduction i put in

for contextual bread crumbs :P

**Comment by macmule** [comment]
As mentioned on JN, same OS isn't needed.

As mentioned on IRC, i'll remove the cache reduction on 10.10 & will add to the beta of the next release (there are a few things in there).

**Comment by macmule** [comment]
Ok, well seems that YoYo has changed the compression format for kernelcache.. A bread crumb to follow, perhaps:

https://pikeralpha.wordpress.com/2014/06/04/os-x-10-10-yosemite-dp1-kernelcache/

**Comment by macmule** [comment]
Ok, I think I have found a workaround.

Can you try:

sudo /usr/bin/hdiutil attach /Library/NetBoot/NetBootSP0/<NBI_NAME>.nbi/NetBoot.dmg -owners on

sudo touch /Volumes//<NBI_NAME>/System/Library/Extensions

sudo /Volumes/10.9.5\ Sun\ 010315/usr/sbin/kextcache -arch x86_64 -L -N -K /Volumes/1/<NBI_NAME>/mach_kernel -c /Library/NetBoot/NetBootSP0//<NBI_NAME>.nbi/i386/x86_64/kernelcache /Volumes//<NBI_NAME>/System/Library/Extensions/

sudo /usr/bin/hdiutil detach /Library/NetBoot/NetBootSP0/<NBI_NAME>.nbi/NetBoot.dmg

That should generate the kernelcache file using 10.9's tool, so the 10.9 NBI should then be NetBoot-able

**Comment by macmule** [comment]
Resolved in 1.1.5, seems a change with 10.10.2's kextcache as it was erroring on unsigned kext's in 10.9.x.

Resolution was to use the kextcache found on the NBI we're creating.
