### ISSUE TITLE
AutoCasperNBI reading MB as GB when calculating space

### ISSUE THREAD

**Issue by macmule** [macmule/AutoCasperNBI#18]
See: https://jamfnation.jamfsoftware.com/discussion.html?id=13516

**Comment by macmule** [comment]
Tested on a 2014 Mac Mini & could not reproduce.

**Comment by macmule** [comment]
Tested creating NBI's on a 2014 Mac Mini with 1TB Fusion drive & had no issues.

**Comment by hunty1** [comment]
Just as another data point :)
I've created all of my NBI's with AutoCasperNBI on an iMac with a fusion drive running 10.9.5. No issues creating 10.9 or 10.10 NBI's

**Comment by macmule** [comment]
From dmw3: 

info /dev/disk2s2
   Device Identifier:        disk2s2
   Device Node:              /dev/disk2s2
   Part of Whole:            disk2
   Device / Media Name:      disk image
 
   Volume Name:              Macintosh HD
 
   Mounted:                  Yes
   Mount Point:              /Volumes/Macintosh HD 1
 
   File System Personality:  HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended
   Owners:                   Disabled
 
   Partition Type:           Apple_HFS
   OS Can Be Installed:      No
   Media Type:               Generic
   Protocol:                 Disk Image
   SMART Status:             Not Supported
   Volume UUID:              3BEEDE1F-E218-3032-B04A-2C29639B1756
   Disk / Partition UUID:    0B02B64F-73F4-4030-81CE-C9C6CE2CBB94
 
   Total Size:               17.0 GB (17032208384 Bytes) (exactly 33266032 512-Byte-Units)
   Volume Free Space:        690.3 MB (690290688 Bytes) (exactly 1348224 512-Byte-Units)
   Device Block Size:        512 Bytes
   Allocation Block Size:    4096 Bytes
 
   Read-Only Media:          Yes
   Read-Only Volume:         Yes
   Ejectable:                Yes
 
   Whole:                    No
   Internal:                 No

**Comment by macmule** [comment]
Fixed in 1.1.5. 

Volumes presenting space in MB now return free space as 0GB
