### ISSUE TITLE
There's a toolbar missing...

### ISSUE THREAD

**Issue by neilmartin83** [macmule/AutoCasperNBI#21]
I think AutoCasperNBI could reach the next level if the Ask Toolbar was integrated with it. I'd love to be able to get answers to life's annoying questions whilst waiting for those pesky NetBoot Images to generate! Questions like "where did I leave my keys?", "when spreading peanut butter on toast, is it better to put butter on first or not have any butter at all?", "what came first, the chicken or the egg?", or "why do paper cuts hurt so much?". What an efficient use of one's time that would be!

All you'd need to do is port it to Java...

**Comment by rderewianko** [comment]
+1 to this.

**Comment by macmule** [comment]
Closed as making the place look untidy
