### ISSUE TITLE
"Cannot Read OS Version" from Composer captured OS.dmg's

### ISSUE THREAD

**Issue by macmule** [macmule/AutoCasperNBI#22]
Take an AutoDMG OS.dmg > Restore  > Mount > Capute OS via Composer > unmount > try & open in AutoCasperNBI. Errors "Cannot Read OS Version"

**Comment by macmule** [comment]
Ok.. so the issue seems to be the grep before awk, & bas assumptions I had made in that: https://github.com/macmule/AutoCasperNBI/blob/master/AutoCasperNBI/AutoCasperNBIAppDelegate.applescript#L513 

Basically, a Composer captured OS.dmg contains JUST the OS partition. So hdiutil attach output looks like:

/usr/bin/hdiutil attach ~/Desktop/ComposerHD.dmg
expected   CRC32 $A02AE580
/dev/disk2          	                               	/Volumes/Macintosh HD 1

Whereas an AutoDMG OS.dmg outputs: 

 /usr/bin/hdiutil attach /Volumes/QuickStick/osx-10.10.1-14B25.hfs.dmg
expected   CRC32 $32279B63
/dev/disk3          	GUID_partition_scheme          	
/dev/disk3s1        	EFI                            	
/dev/disk3s2        	Apple_HFS                      	/Volumes/Macintosh HD 2
/dev/disk3s3        	Apple_Boot     

As horrible as the below looks, it returns the correct mount path for both of the above DMGs:

/usr/bin/hdiutil attach /Volumes/QuickStick/osx-10.10.1-14B25.hfs.dmg | awk -F\"[<>]\" 'a{print $3; exit}$2==\"key\"&&$3==\"mount-point\"{a=1}'

Now we're parsing as a plist & awking out what we need, granted not anywhere near "best practice" but seems to resolve this issue.

Other attempts involved writing a plist & reading from that, but the nested dicts within the arrays gave me some grief (examples below) & with the above working.. i'll put the above into 1.1.5.

Better/more elegant solutions welcome, as long as they can be ran within an AppleScript Objective-C app.

Composer captured OS.dmg
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>system-entities</key>
	<array>
		<dict>
			<key>dev-entry</key>
			<string>/dev/disk2</string>
			<key>mount-point</key>
			<string>/Volumes/Macintosh HD 1</string>
			<key>potentially-mountable</key>
			<true/>
			<key>volume-kind</key>
			<string>hfs</string>
		</dict>
	</array>
</dict>
</plist>

AutoDMG OS.dmg:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>system-entities</key>
	<array>
		<dict>
			<key>content-hint</key>
			<string>GUID_partition_scheme</string>
			<key>dev-entry</key>
			<string>/dev/disk3</string>
			<key>potentially-mountable</key>
			<false/>
			<key>unmapped-content-hint</key>
			<string>GUID_partition_scheme</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>EFI</string>
			<key>dev-entry</key>
			<string>/dev/disk3s1</string>
			<key>potentially-mountable</key>
			<true/>
			<key>unmapped-content-hint</key>
			<string>C12A7328-F81F-11D2-BA4B-00A0C93EC93B</string>
			<key>volume-kind</key>
			<string>msdos</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_HFS</string>
			<key>dev-entry</key>
			<string>/dev/disk3s2</string>
			<key>mount-point</key>
			<string>/Volumes/Macintosh HD 2</string>
			<key>potentially-mountable</key>
			<true/>
			<key>unmapped-content-hint</key>
			<string>48465300-0000-11AA-AA11-00306543ECAC</string>
			<key>volume-kind</key>
			<string>hfs</string>
		</dict>
		<dict>
			<key>content-hint</key>
			<string>Apple_Boot</string>
			<key>dev-entry</key>
			<string>/dev/disk3s3</string>
			<key>potentially-mountable</key>
			<true/>
			<key>unmapped-content-hint</key>
			<string>426F6F74-0000-11AA-AA11-00306543ECAC</string>
			<key>volume-kind</key>
			<string>hfs</string>
		</dict>
	</array>
</dict>
</plist>

**Comment by macmule** [comment]
![alt text](https://pbs.twimg.com/media/B-jEGR7CQAAo3KW.png:large "Logo Title Text 1")

**Comment by macmule** [comment]
fixed in 1.1.5

**Comment by TGBX** [comment]
When will 1.1.5 be released?

**Comment by macmule** [comment]
Also, to add that Composer 9.7 can now capture the Recovery HD, which would have resolved this issue too.
