### ISSUE TITLE
Enhancement: Reduce DMG size further by using .sparseimage

### ISSUE THREAD

**Issue by hunty1** [macmule/AutoCasperNBI#4]
Hey just a suggestion that it should be possible to further reduce the filesize of the finished DMG by converting it to a sparseimage [ hdiutil convert -format UDSP /path/NetBoot.dmg -o /outputPath/NetBoot.sparseimage ] 
This can be symlinked ala Deploy studio to NetBoot.dmg inside the nbi folder so you have
NetBoot.dmg -> NetBoot.sparseimage

This should take the filesize down from around 7.5Gb to about 4.5Gb

**Comment by macmule** [comment]
Hi Hunty1,

As mentioned on twitter, I had made some changes to AutoCasperNBI to move to sparse images.. only to find that JAMFs NetSUS appliance currently doesn't support sparse images without some modification (https://github.com/jamf/NetSUS/issues/53).

AutoCasperNBI generated NBI will be mostly hosted on an OSX Server or NetSUS, as such I'm going to leave the image format as a DMG until the above issue is fixed.

I know there are workarounds to enable sparse image support in NetSUS (http://derflounder.wordpress.com/2012/02/07/modifying-jamfs-netsus-to-host-deploystudio-netboot-boot-sets/), but I am cautious of a) the additional support overhead in this approach (too myself) & b) in moving to sparse images a large amount of AutoCasperNBI had to be re-written, too much to allow user selection of disk format.

It's still a very good idea, & one i'll revisit once the NetSUS supports sparse images.

**Comment by hunty1** [comment]
Roger that. I must admit I did not do any testing with NetSUS, I only use BSDPy these days. Considering the app is called Auto_CASPER_NBI, really should consider who the target market is and what NetBoot Server they are going to use and maximise compatibility for that. I'm probably an outlier... until the people see the light and switch to bsdpy ;) Appreciate your efforts especially considering its AppleScript!
Lets hope that NetSUS gets updated to support sparseimages and/or preserve symlinks when NBI's are uploaded via samba/netatalk

Cheers

**Comment by hunty1** [comment]
Just for my own curiosity I grabbed the NetSUS 3.0.2 OVA

Used the beta of autocaspernbi you sent me to create an NBI with a sparseimage
I simply renamed NetBoot.reduced.sparseimage to NetBoot.reduced.dmg
Uploaded the .nbi folder to the NetSUS and was able to successfully netboot client machines.

**Comment by macmule** [comment]
In 1.1.5

**Comment by macmule** [comment]
To expand apon the above, a sparseimage is now created. 

As NetSUS doesn't support sparseimages, the NBI is renamed .dmg if "Hosted on NetSUS" is ticked.
