### ISSUE TITLE
Hidden content in success popup

### ISSUE THREAD

**Issue by MScottBlake** [macmule/AutoCasperNBI#42]
In version 1.1.7, this is what the Success popup looks like:
![screenshot 2015-03-23 21 21 56](https://cloud.githubusercontent.com/assets/945258/6793995/e5473980-d1a2-11e4-99af-aa365e60c145.png)

**Comment by macmule** [comment]
I'm unsure atm how to resize the text dynamically based on content, but as per https://github.com/macmule/AutoCasperNBI/issues/45 I've added some more buttons to the window.. one will open a Finder window at the NBI's location.

![screen shot 2015-04-10 at 23 58 13](https://cloud.githubusercontent.com/assets/2464974/7098840/9ea53230-dfde-11e4-8c02-e3971a327121.png)

Hope that works for you.
