### ISSUE TITLE
ram disk not hidden

### ISSUE THREAD

**Issue by tkimpton** [macmule/AutoCasperNBI#50]
custom rc.netboot makes the ram disk visible. This can be hidden
solution already posted here https://jamfnation.jamfsoftware.com/discussion.html?id=11356

**Comment by macmule** [comment]
Doh!

Knew I missed one. I'll look into it, but will let the dust settle on 1.2.0 1st. 

Regards,

Ben.

**Comment by macmule** [comment]
Will be fixed in next version

Adding: chflags hidden $mntpt  to rc.netboot where RAM Disk is created

**Comment by macmule** [comment]
in 1.2.1.
