### ISSUE TITLE
Request: Add an option for building a USB drive instead of an NBI

### ISSUE THREAD

**Issue by kitzy** [macmule/AutoCasperNBI#51]
I often end up restoring the DMG within the NBI folder to a USB drive. This works great, but I'd love to have an option to point AutoCasperNBI at an external drive and have it build the drive directly instead of an NBI.

**Comment by macmule** [comment]
Nice idea.. will probably not be in the upcoming release.. but one to think about.

**Comment by macmule** [comment]
So.. i thought about this.. & now with APFS i'm scared to implement.

Sorry fella. 

I'll close this one off for now.
