### ISSUE TITLE
USB Restorable - Certificate Error from JSS

### ISSUE THREAD

**Issue by mturnerfmr** [macmule/AutoCasperNBI#52]
Have built a restorable DMG as well as utilized the DMG created for netboot and applied it to the USB stick. Both methods work for created the DMG, during both methods build time i see it run the step to import the certificate from the JSS. Both have a cert in the correct location, System, when I boot from them. Both throw the error below either at start of build or during the build itself. Continue lets it proceed but after reboot the build process sits at a finishing screen which has no user input available. I believe that it has thrown this message again. The build never finishes. 
Is there something I am missing? Why would this happen if it ran the cert import and it appears to be in place? 
Very new to Casper, have inherited all of this from the Apple OS engineer that left the company.
I have logs as well, just need to figure out how to upload them here.

Thank you.

![casper cert error](https://cloud.githubusercontent.com/assets/13018769/8308557/6fd9b784-1993-11e5-8f25-8d2806487ffa.JPG)

**Comment by macmule** [comment]
Hi mturnerfmr,

Can you please paste into a reply the AutoCasperNBI log from ~/Library/Logs/AutoCasperNBI. Ideally the one from when the DMG was created. 

Also, the ~/Library/Preferences/com.macmule.AutoCasperNBI.plist.. Again from the Mac used to build the DMG. 

On the DMG, can you post the ~/Library/Preferences/com.jamf.casperimaging.plist?

Lastly, can you post a screen shot of the system keychain.. There should be the cert of your JSS there, if it is.. Can you double click it & show the trust levels.

**Comment by macmule** [comment]
See: https://jamfnation.jamfsoftware.com/discussion.html?id=14911

**Comment by macmule** [comment]
Cannot recreate :(

**Comment by mturnerfmr** [comment]
Figured. Every issue that I keep running into here is out of the norm.

Appreciate the help!

Have responded to the post.

Matt

**Comment by macmule** [comment]
Actually, I think this maybe a Casper Imaging issue.

By default, AutoCasperNBI will set Casper Imaging to ignore Invalid certs if a JSS URL is passed to it:

![screenshot 2015-07-21 08 07 07](https://cloud.githubusercontent.com/assets/2464974/8794954/5a12c186-2f80-11e5-88a1-d80567d8688a.png)

If Casper Imaging is not honouring that, then it's a bug with Casper Imaging.

If a JSS URL is not being entered into AutoCasperNBI then it's still a Casper Imaging but as Casper Imaging will not honour the "allowedInvalidCertificate" key. (FR https://jamfnation.jamfsoftware.com/featureRequest.html?id=3781)

**Comment by macmule** [comment]
Closing as cannot recreate :frowning:
