### ISSUE TITLE
Support for Limited access JSS

### ISSUE THREAD

**Issue by rhs615** [macmule/AutoCasperNBI#53]
When entering URL of limited acces JSS, it says cannot connect to get version number. However, I want Casper imaging app in the NBI to point at limited access in case I image somewhere off my main network using a remote distribution point.

**Comment by macmule** [comment]
Thanks rhs615, i'll need to check the logic.. it may also be with a limited access JSS that the JSS's cert cannot be retrieved.

**Comment by macmule** [comment]
1.2.1 now proceeds when can't get cert.. such as a limited access JSS

**Comment by rhs615** [comment]
Thank you!
