### ISSUE TITLE
Removal of the "Date & Time" prefpane

### ISSUE THREAD

**Issue by entusdictus** [macmule/AutoCasperNBI#57]
When the Date & Time pref pane is removed, you are unable to set date & time in the NetBoot image. Here an example why this is an issue:

When you want to image a MacBook with completely empty battery, date and time are not set correctly. As result, the Casper repository can not be mounted. You will first need to boot from another volume, set date and time, and only then the installation will work correctly. 

So, please don't delete the Date & Time prefpane.

**Comment by macmule** [comment]
Fair enough. Will be fixed in next release.

**Comment by macmule** [comment]
Fixed in AutoImagrNBI at: https://github.com/macmule/AutoImagrNBI/blob/master/AutoImagrNBI/AutoImagrNBIAppDelegate.applescript#L2075

Relevant line in AutoCasperNBI:
https://github.com/macmule/AutoCasperNBI/blob/master/AutoCasperNBI/AutoCasperNBIAppDelegate.applescript#L2217

**Comment by macmule** [comment]
In 1.3

**Comment by macmule** [comment]
![screen shot 2015-10-25 at 2 55 53 pm](https://cloud.githubusercontent.com/assets/2464974/10718182/08ccfbfe-7b64-11e5-861f-e72657ea1588.png)
