### ISSUE TITLE
10.11: Deleting dockfixup error

### ISSUE THREAD

**Issue by macmule** [macmule/AutoCasperNBI#58]

**Comment by macmule** [comment]
Issue with logic looking for 10.10 & doing actions.. should look for OS which is greater than 10.9

**Comment by macmule** [comment]
Fixed in 1.3

**Comment by quedayone** [comment]
Awesome!

**Comment by zvordauk** [comment]
Recreated this today. Log files below

Mon Oct 5 13:08:18 IST 2015 Successfully created NetBoot.sparseimage in '/Volumes/JetDrive/nbi v2/10.11 AutoCasperNBI.nbi'
Mon Oct 5 13:08:19 IST 2015 Trying to mount: '/Volumes/JetDrive/nbi v2/10.11 AutoCasperNBI.nbi'
Mon Oct 5 13:08:20 IST 2015 Mounted to: /Volumes/10.11 AutoCasperNBI 1
Mon Oct 5 13:08:20 IST 2015 Copying contents of '/Volumes/Macintosh HD 1' to '/Volumes/JetDrive/nbi v2/10.11 AutoCasperNBI.nbi'/NetBoot.sparseimage
Mon Oct 5 13:30:29 IST 2015 Successfully copied '/Volumes/JetDrive/ElCap-AutoDMG.dmg' to '/Volumes/JetDrive/nbi v2/10.11 AutoCasperNBI.nbi'/NetBoot.sparseimage
Mon Oct 5 13:30:29 IST 2015 NetBoot reduction not enabled. Skipping...
Mon Oct 5 13:30:29 IST 2015 Deleting /Volumes/10.11 AutoCasperNBI 1/private/var/vm/swapfile*
Mon Oct 5 13:30:30 IST 2015 Deleted swapfiles in /Volumes/10.11 AutoCasperNBI 1/private/var/vm/
Mon Oct 5 13:30:31 IST 2015 Deleting /Volumes/10.11 AutoCasperNBI 1/private/var/vm/sleepimage
Mon Oct 5 13:30:31 IST 2015 Deleted sleepimage in /Volumes/10.11 AutoCasperNBI 1/private/var/vm/
Mon Oct 5 13:30:31 IST 2015 Emptying /Volumes/10.11 AutoCasperNBI 1/private/tmp/*
Mon Oct 5 13:30:31 IST 2015 Emptied /Volumes/10.11 AutoCasperNBI 1/private/tmp/
Mon Oct 5 13:30:31 IST 2015 Emptying /Volumes/10.11 AutoCasperNBI 1/private/var/tmp/*
Mon Oct 5 13:30:31 IST 2015 Emptied /Volumes/10.11 AutoCasperNBI 1/private/var/tmp/
Mon Oct 5 13:30:31 IST 2015 Emptying /Volumes/10.11 AutoCasperNBI 1/Volumes/
Mon Oct 5 13:30:32 IST 2015 Emptied /Volumes/10.11 AutoCasperNBI 1/Volumes/
Mon Oct 5 13:30:32 IST 2015 Emptying /Volumes/10.11 AutoCasperNBI 1/dev/
Mon Oct 5 13:30:32 IST 2015 Emptied /Volumes/10.11 AutoCasperNBI 1/dev/
Mon Oct 5 13:30:32 IST 2015 Emptying /Volumes/10.11 AutoCasperNBI 1/var/run/
Mon Oct 5 13:30:32 IST 2015 Emptied /Volumes/10.11 AutoCasperNBI 1/var/run/
Mon Oct 5 13:30:32 IST 2015 Deleting /Volumes/10.11 AutoCasperNBI 1/System/Library/CoreServices/Software Update.app
Mon Oct 5 13:30:33 IST 2015 Deleted /Volumes/10.11 AutoCasperNBI 1/System/Library/CoreServices/Software Update.app
Mon Oct 5 13:30:33 IST 2015 Deleting /Volumes/10.11 AutoCasperNBI 1/System/Library/LaunchDaemons/com.apple.softwareupdate*
Mon Oct 5 13:30:33 IST 2015 Deleted /Volumes/10.11 AutoCasperNBI 1/System/Library/LaunchDaemons/com.apple.softwareupdate*
Mon Oct 5 13:30:33 IST 2015 Deleting /Volumes/10.11 AutoCasperNBI 1/Library/Preferences/SystemConfiguration/preferences.plist
Mon Oct 5 13:30:33 IST 2015 Deleted /Volumes/10.11 AutoCasperNBI 1/Library/Preferences/SystemConfiguration/preferences.plist
Mon Oct 5 13:30:33 IST 2015 Deleting /Volumes/10.11 AutoCasperNBI 1/Library/Preferences/SystemConfiguration/NetworkInterfaces.plist
Mon Oct 5 13:30:33 IST 2015 Deleted /Volumes/10.11 AutoCasperNBI 1/Library/Preferences/SystemConfiguration/NetworkInterfaces.plist
Mon Oct 5 13:30:34 IST 2015 .AppleSetupDone written to /Volumes/10.11 AutoCasperNBI 1/var/db/.AppleSetupDone
Mon Oct 5 13:30:34 IST 2015 .SetupRegComplete written to /Volumes/10.11 AutoCasperNBI 1/Library/Receipts/.SetupRegComplete
Mon Oct 5 13:30:34 IST 2015 Deleting '/Volumes/10.11 AutoCasperNBI 1'/System/Library/CoreServices/Setup Assistant.app
Mon Oct 5 13:30:38 IST 2015 Deleted '/Volumes/10.11 AutoCasperNBI 1'/System/Library/CoreServices/Setup Assistant.app
Mon Oct 5 13:30:38 IST 2015 Disk Utility's Debug Menu enabled
Mon Oct 5 13:30:40 IST 2015 com.apple.TimeMachine.plist amended at /Volumes/10.11 AutoCasperNBI 1/Library/Preferences/com.apple.TimeMachine.plist
Mon Oct 5 13:30:40 IST 2015 Deleting /Volumes/10.11 AutoCasperNBI 1/Library/Preferences/com.apple.dockfixup.plist
Mon Oct 5 13:30:41 IST 2015 Error: Deleting /Library/Preferences/com.apple.dockfixup.plist

^^^ Dies here.

**Comment by ThomasHolbrook** [comment]
Hi, 

"/System/Library/CoreServices/Dock.app/Contents/Resources/com.apple.dockfixup.plist" doesn't seem to exist in our case. 

We have wrapped it in a try for now to work around the issue: 

                try
                
                do shell script "/bin/rm " & quoted form of netBootDmgMountPath & "/System/Library/CoreServices/Dock.app/Contents/Resources/com.apple.dockfixup.plist" user name adminUserName password adminUsersPassword with administrator privileges
                --Log Action
                
                end try


Thanks, 

Tom

**Comment by macmule** [comment]
Hi Thomas,

Was this with the latest commit?


Regards,

Ben.

**Comment by ThomasHolbrook** [comment]
I pulled it down maybe 30 minutes before so it should be? Have i missed something stupid?

**Comment by macmule** [comment]
Might be me then. 

I may be able to work in something tonight, I have an idea about the other issues. 

Regards,

Ben.

**Comment by ThomasHolbrook** [comment]
Cool, look forward to them! 

I just checked and the info says: 

	<key>CFBundleShortVersionString</key>
	<string>1.3.0</string>

Cheers, 

Tom
