### ISSUE TITLE
10.11: SIP enabled

### ISSUE THREAD

**Issue by macmule** [macmule/AutoCasperNBI#63]
Below is from a 1.3 created 10.11 NBI:

<img width="1136" alt="screenshot 2015-09-29 21 03 34" src="https://cloud.githubusercontent.com/assets/2464974/10241177/65c9a88c-68dd-11e5-9d89-394f063e82ac.png">

Seems like SIP might be enabled on a SIU creating NBI.. to investigate

**Comment by everetteallen** [comment]
I was able to add the Automator action to "Bless NetBoot Server" and create a working NetInstall for SIU.

**Comment by macmule** [comment]
Same issue when creating a 10.11 NetBoot Image via SIU.

csrutil is only manageable when in recovery/NetInstall

**Comment by macmule** [comment]
See: https://macmule.com/2015/10/02/autocaspernbi-autoimagrnbi-el-capitan/#Update
