### ISSUE TITLE
Error: Deleting /Library/Preferences/com.apple.dockfixup.plist

### ISSUE THREAD

**Issue by rquigley-woodleigh** [macmule/AutoCasperNBI#64]
Hi,

I'm attempting to build a package with El Capitan, Casper Imaging 9.81 and am having the issue where the program refuses to delete the com.apple.dockfixup.plist.

I've attached a screenshot and logs in hope that something can be found.

Ta.

<img width="533" alt="screen shot 2015-10-21 at 11 57 46 am" src="https://cloud.githubusercontent.com/assets/13759310/10625096/112490a4-77eb-11e5-9c1c-cbfd37a9dfdc.png">

http://pastebin.com/iGzBBimc

#58 (This is a repeat of issue 58 but I hoped this would provide maybe some more information)

**Comment by kevinstrick** [comment]
I think this is because of SIP won't allow modifications in /System ...  i think i workaround might be to disable SIP on the machine you are creating the netboot on (I'm going to try that), but longterm i'm thinking that removing dockfixup is no longer an option

**Comment by kevinstrick** [comment]
nevermind, not SIP it's in /LIbrary...

**Comment by kevinstrick** [comment]
or rather, com.apple.dockfixup.plist is no longer in /Library

**Comment by macmule** [comment]
Resolved in 1.3.0, which was released last night. 

Thanks for the information.
