### ISSUE TITLE
Multiple Casper Imaging in Dock

### ISSUE THREAD

**Issue by macmule** [macmule/AutoCasperNBI#66]
Appears to have arisen with an update to Casper Imaging.

![screen shot 2015-10-25 at 2 56 21 pm](https://cloud.githubusercontent.com/assets/2464974/10718162/f4b0acd8-7b63-11e5-8820-9c10a0790137.png)

**Comment by abdiaziz** [comment]
Just adding in that I'm also experiencing the same issue with Casper Imaging 9.81 and OS X 10.11.1. No problem with Casper Imaging 9.81 and OS X 10.10.5

**Comment by macmule** [comment]
Recreated with 9.81 on a VM running 10.11.2:

https://macmule.com/CasperImaging-Chopped.mp4

**Comment by macmule** [comment]
Created an FR on JAMFNation: https://jamfnation.jamfsoftware.com/featureRequest.html?id=4245

**Comment by macmule** [comment]
Seems to be resolved with Jamf Imaging
