### ISSUE TITLE
Run Full Finder in El Cap

### ISSUE THREAD

**Issue by n0brainer** [macmule/AutoCasperNBI#67]
Doesn't seem to work, at least with a FV2 enabled drive where you didn't enter the password (hit cancel).  Choose run full finder and it never switches over.

**Comment by macmule** [comment]
Oh. So simple Finder on 10.11 no worky?

Regards,

Ben.

**Comment by n0brainer** [comment]
I have the NBI to use the simple finder, but switching back to full finder doesn't work.

**Comment by macmule** [comment]
Ok. I'll see what I can come up with. 

Most probably will need to log a bug with Apple. 

Regards,

Ben.

**Comment by macmule** [comment]
Tested in 10.11 VM & confirmed as a 10.11 bug. 23352376.

I'll update with a response from Apple.

**Comment by abdiaziz** [comment]
Just adding in that I'm also experiencing the same issue with Casper Imaging 9.81 and OS X 10.11.1.

**Comment by macmule** [comment]
I have a pre-release of AutoCasperNBI 1.3.1 available: https://github.com/macmule/AutoCasperNBI/releases/tag/1.3.1

This has a warning like the below when enabling Simple Finder for a 10.11 NBI or trying to build a 10.11 NBI with Simple Finder enabled:
![screen shot 2015-11-16 at 09 26 29](https://cloud.githubusercontent.com/assets/2464974/11189421/e7bd6892-8c87-11e5-9740-5fbfe7da3083.png)

**Comment by macmule** [comment]
Can you please test & feedback?

**Comment by abdiaziz** [comment]
Is it normal for that popup to happen twice? Once when selecting Simple Finder, the other when entering your admin credentials?

**Comment by macmule** [comment]
Yep. 

For now. 

It's an interim prompt, it'll alert when enabled & then pre-build if enabled. 

That's a catch all. Might be a little naggy, but hopefully not having to build NBI's that often &/or Apple resolve soon.

**Comment by abdiaziz** [comment]
Switching to Full finder does not work in OS X 10.11.2

**Comment by macmule** [comment]
Cheers for the update!

No update on my bug.

**Comment by abdiaziz** [comment]
Hey @macmule, I'm guessing Apple hasn't said anything yet?

As for Simple Finder in OS X 10.11.3, it still doesn't work.

I tested this by letting AutoCsaperNBI create an NBI with "Simple Finder" enabled. After accepting the warnings and booting into the NBI, everything seem normal until I noticed that "Simple Finder" wasn't even enabled. The default and only thing working (using AutpCasperNBI) is "Full Finder".

**Comment by macmule** [comment]
@abdiaziz Nothing.. no response to the bug report :(

**Comment by macmule** [comment]
To test on Sierra.. I no longer have access to bug reporter with the account I filed the bug under originally (silly me).

**Comment by macmule** [comment]
Sierra seems better behaved. So looks like a 10.11 issue.

Therefore, ACNBI has a workaround (the alert), the fix is not using 10.11 :(
