### ISSUE TITLE
10.11.2 ARD/VNC Unable to Authenticate

### ISSUE THREAD

**Issue by TSPARR** [macmule/AutoCasperNBI#75]
I tried originally with 1.3.1 and then again with 1.3.2 and was unable to successfully VNC or ARD to the Netboot image. I was able to receive a login prompt, but unable to authenticate. Please let me know if you'd like any logs or have any questions.

**Comment by macmule** [comment]
@TSPARR On the mac that built the NBI, can you check the contents of ~/Library/Preferences/com.macmule.autocaspernbi.plist?

That will show the username & password for ARD.

Also, are you adding any additional PKGs?

**Comment by TSPARR** [comment]
I checked that file and the username and password are the same one I was attempting to use. I've attached a sanitized version of it here: 
[com.macmule.autocaspernbi.txt](https://github.com/macmule/AutoCasperNBI/files/62549/com.macmule.autocaspernbi.txt)

As you can see from the plist, I am also installing Carbon Copy Cloner. Here's a screenshot of the files it's modifying: 
<img width="277" alt="screen shot 2015-12-15 at 08 59 47" src="https://cloud.githubusercontent.com/assets/12848714/11812602/d930eeea-a30a-11e5-9ef2-7d724372d5bb.png">

Just to be clear, the Netboot portion is working fine and I'm able to image computers if I'm physically sitting in front of it. I'm just unable to connect over VNC or ARD. I was attempting to connect from a 10.10.5 computer, but I was able to connect over ARD prior to netbooting the computer.

Thank you,

Tyler Sparr

**Comment by macmule** [comment]
Odd. 

I always connect via ARD. 

What if you delete the Mac from ARD & re-add? Does that work?

Regards,

Ben.

**Comment by TSPARR** [comment]
I just tried setting up a new NBI with a brand new download of OS X 10.11.2, new download of AutoDMG, and new download of AutoCasperNBI. 

Here is the sanitized setup log in which I'm not seeing any errors: 
[AutoCasperNBI-2015-12-15.txt](https://github.com/macmule/AutoCasperNBI/files/62917/AutoCasperNBI-2015-12-15.txt)

This is what the Sharing preference pane looks like in the created Netboot: 
![screen shot 2015-12-15 at 11 48 04 am](https://cloud.githubusercontent.com/assets/12848714/11817617/b387c33a-a323-11e5-8674-695b3694766d.png)
![screen shot 2015-12-15 at 11 53 36 am](https://cloud.githubusercontent.com/assets/12848714/11817651/e77fd57e-a323-11e5-9478-556c932008a8.png)


As you can see, Remote Management is actually turned off and I'm unable to turn it back on. I was able to turn on SSH, but again couldn't authenticate. Here's the log from the Netboot itself showing my attempted authentication: 
[Authentication Attempts.txt](https://github.com/macmule/AutoCasperNBI/files/62921/Authentication.Attempts.txt)

I can get authentication prompts both through VNC and ARD. This is a completely fresh connection.
<img width="542" alt="screen shot 2015-12-15 at 11 48 22" src="https://cloud.githubusercontent.com/assets/12848714/11817680/05b8f548-a324-11e5-88b0-8dca57a5f9d4.png">
<img width="467" alt="screen shot 2015-12-15 at 11 48 55" src="https://cloud.githubusercontent.com/assets/12848714/11817679/05b84d8c-a324-11e5-9bca-1e494b1512ee.png">

Again, I'm open to trying anything or sending more logs. Just let me know what you need.

Much appreciated,

Tyler

**Comment by hunty1** [comment]
ACNBI 1.3.2
AutoDMG 1.5.4
OS: 10.11.2
Created NBI on OS 10.10.5

I came here to create an issue for this exact thing.

I'm seeing the same results as above. remote management _not_ enabled, screen sharing _is_ enabled, but unable to login using the ARD account. VNC password also does not work, I get this error when trying to connect over VNC.

![screen shot 2015-12-17 at 10 23 20 am](https://cloud.githubusercontent.com/assets/7887711/11856970/af39a74a-a4a8-11e5-8240-93c2394f672c.png)


I can connect using screen sharing if i use username: root password: netboot

Perhaps its a 10.11.2 thing

**Comment by macmule** [comment]
Thanks @TSPARR & @hunty1. 

So it seems like ARD is being enabled but the user is not being created.

The script that runs to create the user (amongst other things) is: https://github.com/macmule/AutoCasperNBI/blob/master/AutoCasperNBI/Boot.sh
 
& should be located within /Library/Application Support/AutoCasperNBI/Scripts/ on the NBI

Can you test that script on the NBI? Any errors?

**Comment by hunty1** [comment]
Yep I was going to do that before I left work today but ran out of time. I have to create a new NBI because SSH isn't enabled and I'm running simple finder on this one and couldn't get to terminal d'oh!

Am I missing an option to enable SSH? Or is that not a feature of ACNBI? No biggie easy enough to package up a launchd to do it and add it as an additional item.

I'll give it a crack tomorrow morning mate.

**Comment by macmule** [comment]
@hunty1 Thanks.. i've found some time to test today :) SSH isn't an option, but tbh.. it's meant to be an NBI for a GUI app.. so seemed like more pain that it's worth!

**Comment by macmule** [comment]
Really odd.. working for me (screenshot is taken from ARD)
![10 11 2-ard](https://cloud.githubusercontent.com/assets/2464974/11865175/422702f0-a49a-11e5-90db-74ca191faad7.png)

I'll try again with an NBI that has been reduced.

**Comment by macmule** [comment]
@TSPARR FWIW, you need JSS 9.8.x to manage 10.11

**Comment by macmule** [comment]
![screen shot 2015-12-17 at 2 52 05 am](https://cloud.githubusercontent.com/assets/2464974/11867957/815e74c8-a4ac-11e5-9b3c-d1b7a3f8d0c4.png)

There we go

**Comment by macmule** [comment]
This only happens on a reduced NetBoot FWIW

**Comment by TSPARR** [comment]
@macmule Yeah, I'm aware. We had some show-stopping bugs with our test instance of 9.81, so we're waiting for 9.82. You can still push packages through Casper Imaging from a Netboot or Target Disk Mode to an 10.11 computer though and we got a few new iMacs in that can't boot to 10.10 anymore, so we were just trying to create a quick workaround.

 I like reducing the Netboot as it just presents fewer options and really only gives the bare minimum needed, but it's good to know that we can get around it by either using the root account or not reducing the image.

**Comment by macmule** [comment]
@TSPARR & @hunty1 I found the issue.

So ARD fails on 10.11.2 when the folder /Library/Application Support/Apple/Remote Desktop/ is not there.. it can be empty.. but needs to be there.

Can you both:

1. Rename the NetBoot.dmg to NetBoot.sparseimage
2. Mount NetBoot.sparseimage
3. Create the /Library/Application Support/Apple/Remote Desktop/ folder structure
4. Unmount  NetBoot.sparseimage
5. Rename the NetBoot.sparseimage to NetBoot.dmg

The boot off to the NBI & try again?

**Comment by TSPARR** [comment]
@macmule That's perfect! Worked like a charm. Also, that's a really good secondary tip on editing a read-only DMG. I never knew you could just change the extension and edit it like that.

**Comment by macmule** [comment]
@TSPARR Thanks for logging the issue!

The NetBoot.dmg is actually a sparse image, but is renamed for BSDPy & NetSUS.

It's detailed at: https://macmule.com/projects/autocaspernbi/#Read-Only_DMG & might not work for other DMG's though.

Ironically, @hunty1 is partly responsible.

I'll update AutoCasperNBI tomorrow, i'll manually create the dir when creating the NBI

**Comment by macmule** [comment]
Blogged it: https://macmule.com/2015/12/18/10-11-2-cannot-enable-ard-or-vnc-if-libraryapplication-supportappleremote-desktop-is-missing/

1.3.3 with a fix for this is coming.

Thanks @TSPARR & @hunty1
