### ISSUE TITLE
Error: Disabling Software Update

### ISSUE THREAD

**Issue by zenticles** [macmule/AutoCasperNBI#77]
Fri Jan 29 11:54:34 AEST 2016 Deleted /Volumes/10.9.5 AutoCasperNBI/System/Library/CoreServices/Software Update.app
Fri Jan 29 11:54:34 AEST 2016 Deleting /Volumes/10.9.5 AutoCasperNBI/System/Library/LaunchDaemons/com.apple.softwareupdate*
Fri Jan 29 11:54:35 AEST 2016 Error: Disabling Software Update

Cannot create NBI due to this error. Have tried with several different images as well as on 10.11 and 10.9.

**Comment by macmule** [comment]
@zenticles Have the OS.dmg's your supplying been modified?

It seems like those files have been deleted on the OS.dmg. 

A clean OS.dmg via AutoDMG should work fine.

**Comment by zenticles** [comment]
@macmule It seems as though the images we were using were dirty. Clean image from the App Store and AutoDMG worked fine.

Thanks!
