### ISSUE TITLE
Prevent the use of root as an ARD username

### ISSUE THREAD

**Issue by bp88** [macmule/AutoCasperNBI#81]
This is an enhancement request. Currently, if you attempt to use ARD and use "root" as the username, the resulting netboot image will not auto login. And the default password for root will not work at the Login Window. This request is to prevent the AutoCasperNBI from using "root" as the ARD username so as the avoid any conflicts with the root account already used by default for auto login.

**Comment by macmule** [comment]
In 1.3.4

<img width="532" alt="screenshot 2016-09-09 23 59 50" src="https://cloud.githubusercontent.com/assets/2464974/18405397/9526b50a-76e9-11e6-8ce2-c23e62220a2c.png">
