### ISSUE TITLE
Cannot get JSS version on Limited JSS

### ISSUE THREAD

**Issue by cvgs** [macmule/AutoCasperNBI#82]
ACNBI is not able to get the JSS version number if the JSS URL points to a "Limited JSS".

This might be worked around by using the following method to check the JSS version number (which works on both Limited and Full JSS instances):

```
curl https://my.jss.url:8443/index.cxml
<jamfServlet version=9.81><epoch>1471953159</epoch></jamfServlet>
```

Kind regards,
Christoph

**Comment by cvgs** [comment]
Hi,

the JSS is a clustered environment (3 servers) hosted on Windows. The difference to #79 is that the JSS servers answering to the "JSS URL" are set to "Limited JSS", this disables the normal output ACNBI is expecting:

```
curl -k https://my.jss.url:8443/jss.html -m 30
<html>
	<body>
		<table class="alignLeft" width="100%" border=0>
			<tr>
				<td align="left">
					<h1>Web Application Disabled</h1>
					<font class="assistantNote">
						Your web application has been disabled.
						<BR/><BR/>
					</font>
				</td>
			</tr>
		</table>
	</body>
```

**Comment by macmule** [comment]
hmm.. can you try:

`/usr/bin/curl -k <jssURL> /index.cxml -m 30 | /usr/bin/awk 'BEGIN { FS = "=|<|>" }{ print $3 }'`

**Comment by cvgs** [comment]
Works on 9.81 and 9.93.

It would probably be cleaner to parse the XML, but xmllint complains that it isn't well-formed anyways...

**Comment by macmule** [comment]
yea, I tried some XPath.. but didn't have much luck their either

**Comment by macmule** [comment]
Hey folks,

Can you try: `/usr/bin/curl -k <jssURL>/index.cxml -m 30 | /usr/bin/awk 'BEGIN { FS = "=|<|>" }{ print $3 }'`

**Comment by macmule** [comment]
@cvgs Can you try this in Script Editor?

```
set jssURL to "https://<enter JSS URL HERE>"

set jssURLHtml to do shell script "/usr/bin/curl -k " & jssURL & "/index.cxml -m 30"

-- Store delimiters for resetting later
set applescriptsDelims to AppleScript's text item delimiters
-- We only need the content between the title tags
set startTag to "<jamfServlet version="
set endTag to "><epoch>"
-- Split at the <title> tag
set AppleScript's text item delimiters to startTag
set jssVersionCut to text item 2 of jssURLHtml

set AppleScript's text item delimiters to endTag
set jssVersion to text item 1 of jssVersionCut

-- Reset delimiters
set AppleScript's text item delimiters to applescriptsDelims

display dialog "JSS Version is: " & jssVersion
```

**Comment by cvgs** [comment]
Hi,
that script works under 10.12 and 10.11, tested against 9.81 and 9.93 (both limited and normal). Looks good...

**Comment by macmule** [comment]
Thanks @cvgs.

In 1.3.4, coming soon
