### ISSUE TITLE
AutoCasperNBI and Casper Imaging 9.96

### ISSUE THREAD

**Issue by mojo21221** [macmule/AutoCasperNBI#84]
When trying to create a new netboot image with AutoCasperNBI I found that it would not accept the new Casper Imaging 9.96 App. It would complain about a version number and not let you move forward. In looking at the info.plist inside Casper Imaging 9.96 it looked a bit different that the one from Casper Imaging 9.93. My fix was to modify the info.plist in 9.96, but I'm sure many others would rather have things just work.

**Comment by macmule** [comment]
The issue is that ACNBI is looking in the info.plist for CFBundleGetInfoString, I need to change this to: CFBundleShortVersionString

**Comment by macmule** [comment]
In 1.3.4, coming soon
