### ISSUE TITLE
Casper Imaging 9.96 Version (not found)

### ISSUE THREAD

**Issue by Zigrat** [macmule/AutoCasperNBI#90]
![Uploading Casper Imaging 9.73 and 9.96 info.png…]()
There was a change with Casper Imaging application version 9.96 which causes AutoCasperNBI not to find the Casper Imaging.App version which thus won't let your build a Netboot compiled image. I found that Jamf changed the way it handles a few variables within the info.plist file within Casper Imaging contents. It seems they have taken out the <key>CFBundleGetInfoString</key> <string>9.XX</string> within the 9.96. By adding this back into Casper Imaging. App (9.96) within the Info.plist seems to resolve the issue and AutoCasperNBI is able to compile.

**Comment by macmule** [comment]
This has been resolved in 1.3.4 which is in pre-release. 

https://github.com/macmule/AutoCasperNBI/issues/84

Check releases, & you should see the pre-release at the top.
