### ISSUE TITLE
Image does not appear as an option in Mac Server NetInstall

### ISSUE THREAD

**Issue by bkramps** [macmule/AutoCasperNBI#91]
In testing pre-release 1.3.4, after AutoCasperNBI completes, the resulting image is not available in Mac Server Netinstall.  The image is saved to /Library/NetBoot/NetBootSP0 but an extra folder is created which contains the NBI (i.e. /Library/NetBoot/NetBootSP0/MyImage/MyImage.nbi

**Comment by macmule** [comment]
Hi @bkramps, this is to overcome issues such as: https://github.com/macmule/AutoCasperNBI/issues/83

You'll need to copy the .nbi folder to the root of NetBootSP0.

**Comment by bkramps** [comment]
Thank you. Moving the folder does put the image as an option.

**Comment by macmule** [comment]
Great!

It's change that'I'll document, but needed to stop other issues.
