### ISSUE TITLE
'New to Mac?' appears in top-right.

### ISSUE THREAD

**Issue by Draeconis** [macmule/AutoCasperNBI#92]

**Comment by macmule** [comment]
Found it!

`# remove "New to Mac?" notification
if [ -e "${mountPoint}/System/Library/LaunchAgents/com.apple.touristd.plist" ]; then
	/bin/rm -rf "${mountPoint}/System/Library/LaunchAgents/com.apple.touristd.plist"
fi`

**Comment by macmule** [comment]
In 1.4.0
