### ISSUE TITLE
suggestd and cloudkeychainproxy frequent crashes

### ISSUE THREAD

**Issue by plawrenceCCGS** [macmule/AutoCasperNBI#93]
Booting into a macOS 10.12 built nbi results in frequent crashes of suggestd and cloudkeychainproxy services. I am not sure if this affects the imaging process though.

**Comment by macmule** [comment]
@plawrenceCCGS I cannot see these causing issues, & i'd rather keep things as close to what Apple does with SIU.. As such I'll close this off for now
