### ISSUE TITLE
Recovered files in Trash

### ISSUE THREAD

**Issue by rhysforrester** [macmule/AutoCasperNBI#94]
.nbi created with v1.3.4 (104) using OS.dmg created with AutoDMG v1.6 (452) using 10.12.0 (16A323) - host OS is vanilla 16A323.

I've recreated and replicated this 5 times using both NFS and HTTP. Files seen in Trash attached as screenshot - predominantly Fonts.
![screen shot 2016-10-20 at 9 53 00 am](https://cloud.githubusercontent.com/assets/2081963/19541734/e4dfb326-96ab-11e6-92df-7e2488c004e2.png)

**Comment by macmule** [comment]
@rhysforrester thanks.. seen that recently.. I'll need to dig into it.

**Comment by macmule** [comment]
And now cannot recreate the issue..

**Comment by macmule** [comment]
I'l close this one off for now.
