### ISSUE TITLE
Not working with new MacBook Pros with touchbar

### ISSUE THREAD

**Issue by codewhy17** [macmule/AutoCasperNBI#95]
The current AutoCasperNBI does not boot on the new MacBook Pros with Touchbar. Can you all please release a new update?

**Comment by macmule** [comment]
@codewhy17 There are two issues here:

1) The new MBP'a have a forked OS build. So you'll need the correct OS build for them. 
2) This is the real issue, you need to use a USB-C to Ethernet adaptor (or collection of dongles), that are supported via the macOS EFI for NetBooting. 

Can you see the NBI to attempt the boot of the MBP? Does it attempt to NetBoot & kernel panic?

**Comment by codewhy17** [comment]
So I can't even boot the USB. I created the USB using AutoCasperNBI 9.96 with OS 10.12.1

And when I try to boot to the USB in the preboot stage, it gives me the circle with a slash indicating that it can't boot. It never kernel panics but it never loads the USB.

**Comment by macmule** [comment]
@codewhy17 ok. So sounds like you'be use 10.12.1, but not the correct build of 10.12.1 for that model of Mac.

If you have another, i'd try to capture it's HD from Composer or Disk Utility. Then use that for AutoCasperNBI.

**Comment by codewhy17** [comment]
I am capturing using Composer. Looks like it will take a bit. I will pick back up tomorrow and try it out. Thanks for all the insight.

**Comment by macmule** [comment]
@codewhy17 any update?

**Comment by codewhy17** [comment]
Yes. It worked with a captured DMG of the MBP w/ Touchbar HD. It is a different OS build and that made the difference.
