### ISSUE TITLE
Unidentified developer error in 1.3.4

### ISSUE THREAD

**Issue by jjbyers** [macmule/AutoCasperNBI#96]
Hello, great app thanks.

Attempting to launch AutoCasperNBI 1.3.4 says it is from an unidentified developer.  The release notes say it is signed, but it does not appear to be or the signature is invalid.

**Comment by macmule** [comment]
@jjbyers.. yep.. fun right? Signed in XCode.. doesn't always show as signed though.

**Comment by macmule** [comment]
Sortof fixed.. the .app is signed.. 10.13 is happy when downloading via Safari.. pre-10.13 says unknown dev...

¯\_(ツ)_/¯

`codesign --verify --deep --strict --verbose=2` is happy too
