### ISSUE TITLE
Failure to Reboot on 10.12.2 netboot image

### ISSUE THREAD

**Issue by cubandave** [macmule/AutoCasperNBI#99]
I know this may not be because of AutoCasperNBI but it can't hurt to report it. I have escalated to JAMF support.

Also a discussion on JN: https://www.jamf.com/jamf-nation/discussions/22643/

Our new NetBoot running 10.12.2 and Casper imaging 9.96 is not consistently rebooting when the option is selected. It will just quit Casper imaging and stay logged in. rebooting manually start the first script and enrollment properly.

1.      Issues replicated on all our major models
2.      Happens on Virtual machines with Netboot
3.      Happens on multiple Netboot servers
4.      Happened on a NBI created with 10.12.1 as well
6.      Does not happen on our older netboot created with AutoCasper NBI with Mac OS X 10.11.3
 
Excerpt from the debug log.
``
----------------------------------------------------------------------------------------------------------------------------
Executing Async Command (From Array):
'/Applications/Casper Imaging.app/Contents/Support/jamf' 'reboot' '-immediately'
 
1/19/17 1:55:47 AM -
Command Result:``

**Comment by macmule** [comment]
Hey @cubandave. Is this still an issue?

**Comment by macmule** [comment]
Closing off as cannot replicate with current Casper Imaging versions.
